package cn.gsq.graph.actor;

import cn.gsq.graph.task.Util;

import java.util.UUID;

/**
 * Project : galaxy
 * Class : cn.gsq.graph.actor.Actor
 *
 * @author : gsq
 * @date : 2023-03-28 09:45
 * @note : It's not technology, it's art !
 **/
public interface Actor {

    /**
     * Get the pid of the object. Since this is unique per object,
     * it has to be generated by the class that implements Actor interface.
     * @return
     */
    UUID getPid();

    /**
     * This is a callback method to be implemented to execute code for receive.
     * @param fromId
     * @param message
     */
    void receive(UUID fromId, Object message);

    /**
     * The start time is required to calculate the time out to wait for the message
     * to be arrived.
     * The default implementation is to get the current time whenever a message
     * is received.
     * @return
     */
    default long getStartMilliSeconds() {
        return System.currentTimeMillis();
    }
    /**
     * The timeout is used to calculate the wait time until the message arrives.
     * The default is -1 which there is no time out and it waits indefinitely
     * until the message is received.
     * The start time is used to calculate the timeout.
     * @return
     */
    default long getTimeoutMilliSeconds() {
        return -1;
    }
    /**
     * The is used to receive a message from the sender and calculate the timeout.
     * @param fromId
     * @param message
     */
    default void invoke(UUID fromId, Object message) {
        long to = getTimeoutMilliSeconds();
        if (to > 0 && Util.isTimedOut(getStartMilliSeconds(), to)) {
            //TODO: implement timeout message or indicator
            return;
        }
        receive(fromId, message);
    }
    default void register(String alias) {
        Pid.getInstance().register(alias, this);
    }

    default public void send(UUID toId, Object message) {
       Pid.getInstance().send(toId, message, getPid());
    }
    default public void send(String toAlias, Object message) {
        Pid.getInstance().send(toAlias, message, getPid());
    }

}
